---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Install base packages
  apt:
    name:
      - net-tools
      - dnsutils
      - wget
      - curl
      - mc
      - rsync
    state: present
    update_cache: yes
